# Generated by Django 3.2.4 on 2021-06-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Our_Master_Chef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=123)),
                ('degree', models.CharField(max_length=123)),
                ('Description', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
